
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-app-replicant
  labels:
   app: myapp
spec:
 selector:
  matchLabels:
    env: production
 replicas: 6
 template:
   metadata:
     name: nginx-2
     labels:
      env: production
   spec:
    containers:
      - name: nginx
        image: nginx

   

